### PR TITLE
Faiyaz032 validation class

### PR DESCRIPTION
**Pull request by faiyaz032**
This is a simple User Validation system in OOP way

### CODE REVIEW

**Comment by Shohan494** [comment]
@faiyaz032 check the change request please and resubmit

**Comment by faiyaz032** [comment]
@Shohan494 bhaia. Namespace has been added for reuse the class.

**Comment by faiyaz032** [comment]
@Shohan494 bhaia Autoload funcion also has been added on the project! check it out!

**Comment by faiyaz032** [comment]
@Shohan494  bhaia, Autoload used by composer and fixed the issue. Kindly check it out

**Pull request merged**
